### ISSUE TITLE
Requested region: AU915

### ISSUE THREAD

**Issue by ncasaril** [Lora-net/lr1110_modem_driver#1]
The US915 channels do not really allow use of the modem-e firmware in Australia. 
When will further regions, and especially AU915 be made available? 

Especially the channels described here: 
https://www.thethingsnetwork.org/docs/lorawan/frequency-plans.html#au915-928

**Comment by crtag** [comment]
It's been quite a while since this was mentioned to get delivered by the end of Q1. Are there any updates, please? This became a major showstopper for some of the developments.

**Comment by ncasaril** [comment]
(**bump**) Any updates on this?

**Comment by crtag** [comment]
@ncasaril couple of weeks away as I heard

**Comment by matthieuantoine** [comment]
Hello @ncasaril and @crtag, the firmware v1.1.7 now includes region AU915.

**Comment by crtag** [comment]
@matthieuantoine what are the plans for other regions, like AS923? Thanks!

**Comment by matthieuantoine** [comment]
@crtag, the following regions are now available in firmware v1.1.7 ([changelog](https://github.com/Lora-net/radio_firmware_images/blob/master/lr1110/modem/CHANGELOG.md#v117-2021-05-11)):
* AS923 (3 sub-regions included)
* IN865
* KR920
* RU868
* AU915

**Comment by crtag** [comment]
@matthieuantoine Thanks for that! Are there any updates planed to the modem user manuals, they are dated back to September 2020 and lots of things I can see in your code samples are just not covered in any docs.

**Comment by matthieuantoine** [comment]
@crtag The document is currently in final review and will be available shortly on the corporate website.
