### ISSUE TITLE
Ability to set sync-word (private / public)

### ISSUE THREAD

**Issue by ncasaril** [Lora-net/lr1110_modem_driver#2]
As lorawan networks can be either public or private I'm surprised that there is no api to 
change the sync word used for the lorawan modem. Or have I missed something?

**Comment by matthieuantoine** [comment]
There is no such API for now. I've asked the team in charge to add it.

**Comment by matthieuantoine** [comment]
The firmware v1.1.7 now includes the possibility to make this configuration.
