### ISSUE TITLE
Multicast

### ISSUE THREAD

**Issue by gianni2996** [Lora-net/lr1110_modem_driver#3]
Hi everybody,
I'm developing a board with LR110 using modem driver. Does the device supports multicast groups? The user manual doesn't mention this except from where it tells that port 200 is reserved for multi-cast. As I understood the LR1110 supports only class A and C, so if it supports multicast I must configure it in class C, is it right?
Thanks in advance

**Comment by matthieuantoine** [comment]
Hi @gianni2996 - thanks for your question!

The current firmware does not support multicast.
